<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>learnova.LearningService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\learnova.LearningService.Application\learnova.LearningService.Application.csproj" />
	<ProjectReference Include="..\learnova.LearningService.Infrastructure\learnova.LearningService.Infrastructure.csproj" />
	<ProjectReference Include="..\learnova.LearningService.Persistence\learnova.LearningService.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.0" />
  </ItemGroup>

</Project>
